// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.java_version = JavaVersion.VERSION_1_8
    repositories {
        google()
        mavenCentral()
        maven { url "https://andob.io/repository/open_source" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://andob.io/repository/open_source" }
    }
}
